---
- name: Prepare all hosts for installation
  hosts:  node1
  vars:
    path: /opt/whitenfv/k8s
    folders_primary_deploy:
      - "/pv"
      - "/pvc"
      - "/mongo"
      - "/zookeeper"
      - "/ro-db"
    folders_secondary_deploy:
#      - "/kafka" kafka cluster deployed manually for testing purposes
      - "/ro"
      - "/lcm"
      - "/nbi"
      - "/light-ui"
      - "/mon"
      - "/pol"
      - "/ssl"
  tasks:
  - name: label master node with dedicated=master
    command: kubectl label nodes node1 dedicated=master
    ignore_errors: yes

  - name: install openshift for k8s ansible module
    pip:
      name: openshift
    become: yes

  - name: Deploy k8s namespace
    command: kubectl create -f "{{ path }}"/namespace
    ignore_errors: yes

  - name: deploying configmap
    command: kubectl create configmap config-env --from-env-file=/opt/whitenfv/properties/whitenfv.properties --namespace=whitenfv
    ignore_errors: yes

##Deployments in orden just with cli

  - name: Deploy k8s primary folders
    command: kubectl create -f "{{ path }}""{{ item }}"
    loop: "{{ folders_primary_deploy }}"
    ignore_errors: yes

  - pause:
      minutes: 1
      prompt: "Make sure zookeeper, ro-db and mongo are ready before proceeding"

  - name: Deploy k8s kafka cluster
    command: kubectl create -f "{{ path }}"/kafka
    ignore_errors: yes

  - pause:
      minutes: 1
      prompt: "Make sure kafka is ready before proceeding"

  - name: Deploy k8s secondary folders
    command: kubectl create -f "{{ path }}""{{ item }}"
    loop: "{{ folders_secondary_deploy }}"
    ignore_errors: yes
