---
- name: Prepare all hosts for installation
  hosts:  node1
  vars:
    path: /opt/whitenfv/k8s
    folders_primary:
      - "/pv"
      - "/pvc"
      - "/mongo"
      - "/zookeeper"
      - "/kafka"
    folders_secondary:
      - "/ro-db"
      - "/ro"
      - "/lcm"
      - "/nbi"
      - "/light-ui"
      - "/mon"
      - "/pol"
      - "/ssl"
  tasks:

  - name: install openshift for k8s ansible module
    pip:
      name: openshift
    become: yes

  - name: Deploy k8s namespace
    command: kubectl create -f "{{ path }}"/namespace
    ignore_errors: yes

  - name: deploying configmap
    command: kubectl create configmap config-env --from-env-file=/opt/whitenfv/properties/whitenfv.properties --namespace=whitenfv
    ignore_errors: yes

##Deployments in orden just with cli,

  - name: Deploy k8s primary folders
    command: kubectl create -f "{{ path }}""{{ item }}"
    loop: "{{ folders_primary }}"
    ignore_errors: yes

  - name: Deploy k8s secondary folders
    command: kubectl create -f "{{ path }}""{{ item }}"
    loop: "{{ folders_secondary }}"
    ignore_errors: yes
