- name: Juju and OSM client installer
  hosts:  node1
  vars:
    #JUJU
    whitenfv_path: /opt/whitenfv
    images_path: "{{whitenfv_path}}"/images
    juju_image_metadata: "{{ images_path }}"/juju-xenial-amd64
    juju_image_root: "{{ images_path }}"/juju-xenial-amd64.root
    juju_image_alias: juju/xenial/amd64
    #OSM
    mon_port: 30866
    osm_hostname: 127.0.0.1:30999
    release: ReleaseFOUR
    repository: stable
    client_repository_base: https://osm-download.etsi.org/repository/osm/debian
    client_repository_key: OSM%20ETSI%20Release%20Key.gpg

  tasks:

    - name: export lc_all and LANG
      command:  export LC_ALL=en_US.UTF-8 &&  export LANG=en_US.UTF-8
      become_user: whitenfv

    - name: lxc image import
      command: lxc image import "{{ juju_image_metadata} }" "{{ juju_image_root }}" --alias "{{JUJU_IMAGE_ALIAS}}"
      become_user: whitenfv

    - name: snap install juju classic
      command: sudo snap install juju --classic
      become_user: whitenfv
