---
- name: Prepare all hosts for installation
  hosts:  all
  become: true
  tasks:

  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: create whitenfv user
    command: adduser whitenfv
    ignore_errors: yes

  - name: make whitenfv memver of sudo group
    command:  usermod -aG sudo whitenfv
    ignore_errors: yes
    become: yes


  - name: make whitenfv member of lxd group
    command:  usermod -aG lxd whitenfv
    ignore_errors: yes
    become: yes
    
  - name: switch user for future plays
    command: su whitenfv
    ignore_errors: yes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent
