---
- name: Prepare node1 (master) for juju and osm instalation
  hosts:  node1
  become: true
  vars:
    whitenfv_filename: whitenfv-r4_0.15-1_all.deb
    whitenfv_deb_path: "~/Downloads/{{ whitenfv_filename }}"

  tasks:
    ###move the file  whitenfv .deb
  - name: Copy whitenfv.deb from local to master node1
    copy:
      src: "{{ whitenfv_deb_path }}"
      dest: /opt/
      owner: whitenfv
      mode: 777

      ##sudo apt get update
  - name: run apt-get update command
    command: apt-get update
    become: yes

  - name: install pexpect
    pip:
      name: pexpect
    become: yes
    ## command install ./.deb
  - name: install expect for juju bash
    command: apt-get install expect
    become: yes

  - name: run command to install .deb
    expect:
      command:   apt-get install /opt/"{{ whitenfv_filename }}"
      responses:
         Do you want to continue?: 'y'
    become: yes


   - name: "make broken sync module work"
     lineinfile:
       path: /etc/sudoers
       state: present
       regexp: '^%sudo\s'
       line: '%sudo ALL=(ALL) NOPASSWD: ALL'

   - name: cd to /opt/whitenfv/bin and execute juju and osm installer
     command: chdir=/opt/whitenfv/bin    ./whitenfv_juju_osmcli_install.sh
     become: yes
     become_user: whitenfv
     become_flags: -S
     register: juju_output
   - debug: var=juju_output


   - name: "cleanup after sync module"
     lineinfile:
       path: /etc/sudoers
       state: present
       regexp: '^%sudo\s'
       line: '%sudo ALL=(ALL) ALL'
     ## run command . ~/.bashrc
   - name: source bashrc
     command: source  ~/.bashrc
